version: 2.1
jobs:
  build:
    docker:
      - image: node:11
    working_directory: ~/repo
    steps:
      - checkout 
      #download and cache dependancies

      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            # fallback to using the latest cache if no exact match is found

            - v1-dependancies-
      - run: yarn add
        
      - save_cache:
          
            paths:
              - node_modules
            key: v1-dependancies-{{checksum "package.json"}}

      #run tests if there some
      - run: yarn test
        
      - run: yarn build
      
      - run: yarn netlify:deploy
        
        
